---
- name: check for checksum
  fail:
    msg: >
      There is no sha1 checksum defined for version {{ sox_version }} in
      vars/main.yml. Set sox_checksum manually or submit a PR to add this
      version.
  when:
    - sox_verify_checksum|bool
    - sox_checksum is not defined
    - sox_version not in sox_checksums
