---
- name: install dependencies | Debian
  package:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
    state: present
  with_items:
    - gcc
    - make
    - g++
    - autoconf
    - automake
    - libtool
    - libid3tag0-dev
    - libflac-dev
    - patch
  when: ansible_os_family == "Debian"

- name: install dependencies | RedHat
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - make
    - gcc-c++
    - autoconf
    - automake
    - libtool 
    - libid3tag
    - libid3tag-devel
    - flac-devel
    - patch
  when: ansible_os_family == "RedHat"

