---
# get_url on Ansible 1.x only supports sha256 checksumming, so we're only
# using `lame_checksums` on Ansible 2.x because they're sha1.
- name: set lame checksum
  set_fact:
    lame_checksum: "sha1:{{ lame_checksums[lame_version] }}"
  when:
    - lame_verify_checksum|bool
    - lame_checksum is not defined
    - lame_version in lame_checksums
    - ansible_version.major >= 2

- name: download lame (ansible 1.x)
  get_url:
    url: "{{ lame_download_url }}"
    dest: "{{ lame_download_dir }}/lame-{{ lame_version }}.tar.gz"
    sha256sum: "{{ lame_checksum|default(omit) }}"
  when:
    - ansible_version.major < 2

- name: download lame (ansible 2.x)
  get_url:
    url: "{{ lame_download_url }}"
    dest: "{{ lame_download_dir }}/lame-{{ lame_version }}.tar.gz"
    checksum: "{{ lame_checksum|default(omit) }}"
  when:
    - ansible_version.major >= 2

- name: extract lame tarball
  unarchive:
    src: "{{ lame_download_dir }}/lame-{{ lame_version }}.tar.gz"
    dest: "{{ lame_download_dir }}"
    creates: "{{ lame_download_dir }}/lame-{{ lame_version }}/configure"
    copy: no

- name: Run configure 
  command: ./configure --bindir="{{ lame_install_dir }}" --disable-shared --enable-nasm
  args:
    chdir: "{{ lame_download_dir }}/lame-{{ lame_version }}"
    creates: "{{ lame_download_dir }}/lame-{{ lame_version }}/Makefile"

- name: Run make
  command: make -j{{ ansible_processor_cores + 1 }}
  args:
    chdir: "{{ lame_download_dir }}/lame-{{ lame_version }}"
    creates: "{{ lame_download_dir }}/lame-{{ lame_version }}/lame"

- name: Run make install
  command: make install
  args:
    chdir: "{{ lame_download_dir }}/lame-{{ lame_version }}"
    creates: "{{ lame_install_dir }}/lame"
  notify:
    - reload ldconfig
 
- name: Clean up the source files
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ lame_download_dir }}/lame-{{ lame_version }}.tar.gz"
    - "{{ lame_download_dir }}/lame-{{ lame_version }}"
  when: lame_cleanup_downloads|bool 
 