---
- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ sox_package_dependencies }}"

- name: Install EPEL | RedHat
  when:
    - ansible_distribution == "RedHat"
  block:
    - name: Import EPEL GPG key | RedHat
      rpm_key:
        key: "http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
        state: present

    - name: Install EPEL | RedHat
      package:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present

# Install Sox from package
- name: Install base sox package.
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ sox_package_base }}"

# Install additional pacakges for optional audio formats.
- name: Install packages for additional audio formats.
  package:
    name: "{{ item.value.packages }}"
    state: present
  with_dict: "{{ sox_package_optional_formats_config }}"
  loop_control:
    label: "{{ item.key }} - {{ item.value.packages }}"
