---
- name: set lame checksum
  set_fact:
    lame_checksum: "sha1:{{ lame_checksums[lame_version] }}"
  when:
    - lame_verify_checksum|bool
    - lame_checksum is not defined
    - lame_version in lame_checksums

- name: download lame
  get_url:
    url: "{{ lame_download_url }}"
    dest: "{{ lame_download_dir }}/lame-{{ lame_version }}.tar.gz"
    checksum: "{{ lame_checksum|default(omit) }}"

- name: extract lame tarball
  unarchive:
    src: "{{ lame_download_dir }}/lame-{{ lame_version }}.tar.gz"
    dest: "{{ lame_download_dir }}"
    creates: "{{ lame_download_dir }}/lame-{{ lame_version }}/configure"
    copy: no

- name: Run configure | lame
  command: ./configure --bindir="{{ lame_install_dir }}" --enable-nasm
  args:
    chdir: "{{ lame_download_dir }}/lame-{{ lame_version }}"
    creates: "{{ lame_download_dir }}/lame-{{ lame_version }}/Makefile"

- name: Run make | lame
  command: make -j{{ ansible_processor_cores + 1 }}
  args:
    chdir: "{{ lame_download_dir }}/lame-{{ lame_version }}"
    creates: "{{ lame_download_dir }}/lame-{{ lame_version }}/libmp3lame/.libs/libmp3lame.a"

- name: Run make install | lame
  command: make install
  args:
    chdir: "{{ lame_download_dir }}/lame-{{ lame_version }}"
    creates: "{{ lame_install_dir }}/libmp3lame.a"
  notify:
    - reload ldconfig
  become: yes
 
- name: Clean up the source files | lame
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ lame_download_dir }}/lame-{{ lame_version }}.tar.gz"
    - "{{ lame_download_dir }}/lame-{{ lame_version }}"
  when: lame_cleanup_downloads|bool 
 
