---
- name: Install dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ sox_package_dependencies }}"

# Install Sox from package
- name: Install sox package.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ sox_package_base }}"

# Install additional pacakges for optional audio formats.
- name: Install packages for additional audio formats.
  package:
    name: "{{ sox_package_formats_options[ item ] }}"
    state: present
  with_items: "{{ sox_package_formats_options.keys() }}"
  when: item in sox_install_formats
