---
- name: set libogg checksum
  set_fact:
    libogg_checksum: "sha1:{{ libogg_checksums[libogg_version] }}"
  when:
    - libogg_verify_checksum|bool
    - libogg_checksum is not defined
    - libogg_version in libogg_checksums

- name: download libogg
  get_url:
    url: "{{ libogg_download_url }}"
    dest: "{{ libogg_download_dir }}/libogg-{{ libogg_version }}.tar.gz"
    checksum: "{{ libogg_checksum|default(omit) }}"

- name: extract libogg tarball
  unarchive:
    src: "{{ libogg_download_dir }}/libogg-{{ libogg_version }}.tar.gz"
    dest: "{{ libogg_download_dir }}"
    creates: "{{ libogg_download_dir }}/libogg-{{ libogg_version }}/configure"
    copy: no

- name: Run configure | libogg
  command: ./configure
  args:
    chdir: "{{ libogg_download_dir }}/libogg-{{ libogg_version }}"
    creates: "{{ libogg_download_dir }}/libogg-{{ libogg_version }}/Makefile"

- name: Run make | libogg
  command: make -j{{ ansible_processor_cores + 1 }}
  args:
    chdir: "{{ libogg_download_dir }}/libogg-{{ libogg_version }}"
    creates: "{{ libogg_download_dir }}/libogg-{{ libogg_version }}/.libs/libogg.a"

- name: Run make install | libogg
  command: make install
  args:
    chdir: "{{ libogg_download_dir }}/libogg-{{ libogg_version }}"
    creates: "{{ libogg_install_dir }}/libogg.a"
  notify:
    - reload ldconfig
  become: yes
 
- name: Clean up the source files | libogg
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ libogg_download_dir }}/libogg-{{ libogg_version }}.tar.gz"
    - "{{ libogg_download_dir }}/libogg-{{ libogg_version }}"
  when: libogg_cleanup_downloads|bool 
  
 
