# ---
# - name: set flac checksum
#   set_fact:
#     flac_checksum: "sha1:{{ flac_checksums[flac_version] }}"
#   when:
#     - flac_verify_checksum|bool
#     - flac_checksum is not defined
#     - flac_version in flac_checksums

# - name: download flac
#   get_url:
#     url: "{{ flac_download_url }}"
#     dest: "{{ flac_download_dir }}/flac-{{ flac_version }}.tar.xz"
#     checksum: "{{ flac_checksum|default(omit) }}"

# - name: extract flac tarball
#   unarchive:
#     src: "{{ flac_download_dir }}/flac-{{ flac_version }}.tar.xz"
#     dest: "{{ flac_download_dir }}"
#     creates: "{{ flac_download_dir }}/flac-{{ flac_version }}/configure"
#     copy: no

# - name: Run configure  | flac
#   command: ./configure
#   args:
#     chdir: "{{ flac_download_dir }}/flac-{{ flac_version }}"
#     creates: "{{ flac_download_dir }}/flac-{{ flac_version }}/Makefile"

# - name: Run make | flac
#   command: make -j{{ ansible_processor_cores + 1 }}
#   args:
#     chdir: "{{ flac_download_dir }}/flac-{{ flac_version }}"
#     creates: "{{ flac_download_dir }}/flac-{{ flac_version }}/src/libFLAC/.libs/libFLAC.so"

# - name: Run make install | flac
#   command: make install
#   args:
#     chdir: "{{ flac_download_dir }}/flac-{{ flac_version }}"
#     creates: "{{ flac_install_dir }}/libFLAC.so"
#   notify:
#     - reload ldconfig
#   become: yes

# - name: Clean up the source files | flac
#   file:
#     path: "{{ item }}"
#     state: absent
#   with_items:
#     - "{{ flac_download_dir }}/flac-{{ flac_version }}.tar.xz"
#     - "{{ flac_download_dir }}/flac-{{ flac_version }}"
#   when: flac_cleanup_downloads|bool
