---
# get_url on Ansible 1.x only supports sha256 checksumming, so we're only
# using `flac_checksums` on Ansible 2.x because they're sha1.
- name: set flac checksum
  set_fact:
    flac_checksum: "sha1:{{ flac_checksums[flac_version] }}"
  when:
    - flac_verify_checksum|bool
    - flac_checksum is not defined
    - flac_version in flac_checksums
    - ansible_version.major >= 2

- name: download flac (ansible 1.x)
  get_url:
    url: "{{ flac_download_url }}"
    dest: "{{ flac_download_dir }}/flac-{{ flac_version }}.tar.xz"
    sha256sum: "{{ flac_checksum|default(omit) }}"
  when:
    - ansible_version.major < 2

- name: download flac (ansible 2.x)
  get_url:
    url: "{{ flac_download_url }}"
    dest: "{{ flac_download_dir }}/flac-{{ flac_version }}.tar.xz"
    checksum: "{{ flac_checksum|default(omit) }}"
  when:
    - ansible_version.major >= 2

- name: extract flac tarball
  unarchive:
    src: "{{ flac_download_dir }}/flac-{{ flac_version }}.tar.xz"
    dest: "{{ flac_download_dir }}"
    creates: "{{ flac_download_dir }}/flac-{{ flac_version }}/configure"
    copy: no

- name: Run configure 
  command: ./configure --disable-shared
  args:
    chdir: "{{ flac_download_dir }}/flac-{{ flac_version }}"
    creates: "{{ flac_download_dir }}/flac-{{ flac_version }}/Makefile"

- name: Run make
  command: make -j{{ ansible_processor_cores + 1 }}
  args:
    chdir: "{{ flac_download_dir }}/flac-{{ flac_version }}"
    creates: "{{ flac_download_dir }}/flac-{{ flac_version }}/src/libFLAC/.libs/libFLAC.a"

- name: Run make install
  command: make install
  args:
    chdir: "{{ flac_download_dir }}/flac-{{ flac_version }}"
    creates: "{{ flac_install_dir }}/libFLAC.a"
  notify:
    - reload ldconfig
  become: yes
 
- name: Clean up the source files
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ flac_download_dir }}/flac-{{ flac_version }}.tar.xz"
    - "{{ flac_download_dir }}/flac-{{ flac_version }}"
  when: flac_cleanup_downloads|bool 
  
 
