---
- name: Set checksum | sox
  set_fact:
    sox_checksum: "sha1:{{ sox_checksums[sox_version] }}"
  when:
    - sox_verify_checksum|bool
    - sox_checksum is not defined
    - sox_version in sox_checksums

- name: Download tarball | sox
  get_url:
    url: "{{ sox_download_url }}"
    dest: "{{ sox_download_dir }}/sox-{{ sox_version }}.tar.gz"
    checksum: "{{ sox_checksum | default(omit) }}"
    mode: 0644

# The unarchive must change the permissions of the destination folder when mode parameter is supplied.
# But it behaves differently with tar.gz and zip archives.
# When extracting tar.gz, it doesn't touch the destination folder's permissions.
# While in case of extracting zip into something like /tmp/ with mode: 755, it overrides the permissions of /tmp to 755.
# This step will create a direcoty specific to this role to extract files to
- name: Create directory for extracted files
  file:
    path: "{{ sox_download_dir }}/sox"
    state: directory
    mode: u=rwX,g=rX,o=rX
  register: _extract_dir

- name: Extract tarball | sox
  unarchive:
    src: "{{ sox_download_dir }}/sox-{{ sox_version }}.tar.gz"
    dest: "{{ _extract_dir.path }}"
    creates: "{{ _extract_dir.path }}/sox-{{ sox_version }}/configure"
    copy: false

- name: Run configure | sox
  command: ./configure --bindir={{ sox_install_dir }} --with-mp3 {{ _configure_args }}
  args:
    chdir: "{{ _extract_dir.path }}/sox-{{ sox_version }}"
    creates: "{{ _extract_dir.path }}/sox-{{ sox_version }}/Makefile"
  environment:
    LDFLAGS: "-Wl,-rpath={{ sox_compile_default_library_install_dir }}"

- name: Run make | sox
  command: make -j{{ ansible_processor_cores + 1 }}
  args:
    chdir: "{{ _extract_dir.path }}/sox-{{ sox_version }}"
    creates: "{{ _extract_dir.path }}/sox-{{ sox_version }}/src/sox"

- name: Run make install | sox
  command: make install
  args:
    chdir: "{{ _extract_dir.path }}/sox-{{ sox_version }}"
    creates: "{{ sox_install_dir }}/sox"
  notify:
    - Reload ldconfig
  become: true

- name: Clean up the source files | sox
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ sox_download_dir }}/sox-{{ sox_version }}.tar.gz"
    - "{{ _extract_dir.path }}"
  when: sox_cleanup_downloads|bool
