---
# New plan,
# idea is to be able to build sox with new formats by supplying vairiables instead of updating role
#  - install from package y or n
#  - supply list of formats
#     - wav
#     - ogg
#     - mp3
#     - flac
#   - install based on method and list of formats


- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"

# Install Sox and libraries from package when enabled
- include: install_from_package.yml
  become: true
  when: not sox_install_from_source|bool

# Install Sox and libraries from source when enabled
- name: Install from Source
  block:

    - include: check_vars.yml

    - name: check if sox installed
      command: "which {{ sox_install_dir }}/sox"
      register: sox_exists
      ignore_errors: true
      changed_when: false
      failed_when: false

    - include: dependencies.yml
      become: true
      when: sox_exists.rc != 0

    # ----------------------------------
    # lame
    # ----------------------------------
    - name: check if lame installed
      stat:
        path: "{{ lame_install_dir }}/libmp3lame.a"
      register: lame_exists
      ignore_errors: true
      changed_when: false
      failed_when: false
      when: sox_exists.rc != 0

    - include: install_lame_from_source.yml
      when: sox_exists.rc != 0 and lame_exists.stat.exists == false


    # ----------------------------------
    # libmad
    # ----------------------------------
    - name: check if libmad installed
      stat:
        path: "{{ libmad_install_dir }}/libmad.a"
      register: libmad_exists
      ignore_errors: true
      changed_when: false
      failed_when: false
      when: sox_exists.rc != 0

    - include: install_libmad_from_source.yml
      when: sox_exists.rc != 0 and libmad_exists.stat.exists == false


    # ----------------------------------
    # libogg
    # ----------------------------------
    - name: check if libogg installed
      stat:
        path: "{{ libogg_install_dir }}/libogg.a"
      register: libogg_exists
      ignore_errors: true
      changed_when: false
      when: sox_exists.rc != 0

    - include: install_libogg_from_source.yml
      when: sox_exists.rc != 0 and libogg_exists.stat.exists == false

    # ----------------------------------
    # Sox
    # ----------------------------------
    - include: install_from_source.yml
      when: sox_exists.rc != 0

  when: sox_install_from_source|bool
