---
# New plan,
# idea is to be able to build sox with new formats by supplying vairiables instead of updating role
#  - install from package y or n
#  - supply list of formats
#     - wav
#     - ogg
#     - mp3
#     - flac
#   - install based on method and list of formats

# Check for proper configuration
- import_tasks: preflight.yml

# # Install Sox and libraries from package when enabled
- import_tasks: install_from_package.yml
  become: true
  when: not sox_install_from_source|bool

# TODO Need to make this conditional based on the formats supplied
# Install Sox and libraries from source when enabled
- name: Install from Source
  block:

    - import_tasks: check_vars.yml

    - name: check if sox installed
      command: "which {{ sox_install_dir }}/sox"
      register: sox_exists
      ignore_errors: true
      changed_when: false
      failed_when: false

    - import_tasks: dependencies.yml
      become: true
      when: sox_exists.rc != 0

    # ----------------------------------
    # lame
    # ----------------------------------
    - name: check if lame installed
      stat:
        path: "{{ lame_install_dir }}/libmp3lame.a"
      register: lame_exists
      ignore_errors: true
      changed_when: false
      failed_when: false
      when: sox_exists.rc != 0

    - import_tasks: install_lame_from_source.yml
      when: sox_exists.rc != 0 and lame_exists.stat.exists == false


    # ----------------------------------
    # libmad
    # ----------------------------------
    - name: check if libmad installed
      stat:
        path: "{{ libmad_install_dir }}/libmad.a"
      register: libmad_exists
      ignore_errors: true
      changed_when: false
      failed_when: false
      when: sox_exists.rc != 0

    - import_tasks: install_libmad_from_source.yml
      when: sox_exists.rc != 0 and libmad_exists.stat.exists == false


    # ----------------------------------
    # libogg
    # ----------------------------------
    - name: check if libogg installed
      stat:
        path: "{{ libogg_install_dir }}/libogg.a"
      register: libogg_exists
      ignore_errors: true
      changed_when: false
      when: sox_exists.rc != 0

    - import_tasks: install_libogg_from_source.yml
      when: sox_exists.rc != 0 and libogg_exists.stat.exists == false

    # ----------------------------------
    # libvorbis
    # ----------------------------------
    - name: check if libvorbis installed
      stat:
        path: "{{ libvorbis_install_dir }}/libvorbis.a"
      register: libvorbis_exists
      ignore_errors: true
      changed_when: false
      when: sox_exists.rc != 0

    - import_tasks: install_libvorbis_from_source.yml
      when: sox_exists.rc != 0 and libvorbis_exists.stat.exists == false


    # ----------------------------------
    # flac
    # ----------------------------------
    - name: check if libFLAC installed
      stat:
        path: "{{ flac_install_dir }}/libFLAC.so"
      register: flac_exists
      ignore_errors: true
      changed_when: false
      when: sox_exists.rc != 0

    - include: install_flac_from_source.yml
      when: sox_exists.rc != 0 and flac_exists.stat.exists == False

    # ----------------------------------
    # Sox
    # ----------------------------------
    - import_tasks: install_from_source.yml
      when: sox_exists.rc != 0

  when: sox_install_from_source|bool
