---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Set sox_install_from_source to false
      set_fact:
        sox_install_from_source: false

  roles:
    - role: ansible-sox-role
      tags:
        - sox
