---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - set_fact:
        sox_install_from_source: false

    # package `sox` requires `lame-libs`, `libmad`, `wavpack`, `libao`, and `opus`
    # on RHEL8, they would be available via `rhel-8-for-x86_64-appstream-rpms`
    # These are not available on UBI8, installing from CentOS8-appstream repo
    - name: Install dependencies from CentOS Repositories | RHEL 8
      when:
       - ansible_distribution == "RedHat"
       - ansible_distribution_major_version == "8"
      block:

        - set_fact:
            _tmp_repos:
              - name: appstream
                url: http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/
                gpg: http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-Official

            _tmp_packages:
              - name: lame-libs
                repo: appstream
              - name: libmad
                repo: appstream
              - name: wavpack
                repo: appstream
              - name: libao
                repo: appstream
              - name: opus
                repo: appstream

        - name: Add Temporary Repositories | RHEL 8
          yum_repository:
              name: "{{ item.name }}"
              description: "Centos {{ ansible_distribution_major_version }} - {{ item.name }}"
              baseurl: "{{ item.url }}"
              enabled: false
          with_items: "{{ _tmp_repos }}"
          loop_control:
            label: "{{ item.name }}"

        - name: Install missing packages | RHEL 8
          yum:
            name: "{{ item.name }}"
            state: present
            enablerepo: "{{ item.repo }}"
            disable_gpg_check: true
          with_items: "{{ _tmp_packages }}"
          loop_control:
            label: "{{ item.name }}"



    - name: Install prerequisites
      block:
        - name: Update apt cache
          apt:
            update_cache: true
            cache_valid_time: 600
          changed_when: false
          when: ansible_os_family == "Debian"

  roles:
    - role: ansible-sox-role
      tags:
        - sox
