---
name: Ansible role testing
"on":
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  schedule:
    - cron: "30 7 1 * *"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      - name: Install Ansible collections
        run: uv run ansible-galaxy collection install community.general

      - name: Run ansible-lint
        run: uv run ansible-lint

  test1:
    name: molecule(source)
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu2204
          - ubuntu2404
          - rockylinux9
          - rhel9

    steps:
      - name: Check out the Repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      - name: Run molecule test
        run: uv run molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

  test2:
    name: molecule(package)
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu2204
          - ubuntu2404
          - rockylinux9
          - rhel9

    steps:
      - name: Check out the Repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      - name: Run molecule tests, install from Package
        run: uv run molecule test -s install-from-package
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
